spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://database-1.cxbxe7ypeoyt.us-east-1.rds.amazonaws.com/ems_db
    username: admin
    password: 12345678

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
